### ISSUE TITLE
RocketChat Adapter

### ISSUE THREAD

**Issue by DaBlitzStein** [go-chat-bot/bot#38]
It is possible to create a RocketChat adapter?

**Comment by fabioxgn** [comment]
@DaBlitzStein currently there's no plan to do so, but writting an adapter is very simple, you can use the other adapters as example if you'd like to implement it: https://github.com/go-chat-bot/bot/blob/master/slack/slack.go

**Comment by DaBlitzStein** [comment]
It is possible, but maybe I can use a little explanation of how it works!

Thank you!

**Comment by fabioxgn** [comment]
@DaBlitzStein it's very simple, you have to be aware of just 2 methods, I'll use the telegram integration as example as it is simpler:

```Go
   // Creates a new bot instance and provides a responseHandler handler.
   b := bot.New(&bot.Handlers{
		Response: responseHandler,
	})

       // Now we process all the incoming messages from telegram and forward them to the bot
	for update := range updates {
		target := strconv.FormatInt(update.Message.Chat.ID, 10)
		sender := strconv.Itoa(update.Message.From.ID)
		b.MessageReceived(target, update.Message.Text, &bot.User{Nick: sender})
	}
```

The code above is basically everything you need. First you need to instantiate a new bot and provide a `ResponseHandler` func:

```
 b := bot.New(&bot.Handlers{
		Response: responseHandler,
	})
```

This is the func signature: `func responseHandler(target string, message string, sender *bot.User)`

The bot will call this function everytime it replies, so if you use a command like "!hello", the bot will call this function back, in this function you will have to relay the message back to RocketChat.

Then you just have to handle each message comming from RocketChat and forward them to the bot, calling this function:

```Go
b.MessageReceived(target, Message, &bot.User{Nick: sender})
```

In this case, target would be the channel, Message is the message's text, and you need to pass a bot.User with the info about the user which posted the message so that the bot can reply to him.

And that's it.

**Comment by DaBlitzStein** [comment]
Seems that it is not trivial, i can't find api path for read unreaded messages or all message stream.

**Comment by pyinx** [comment]
@DaBlitzStein https://github.com/go-chat-bot/bot/pull/58

**Comment by fabioxgn** [comment]
Fixed in https://github.com/go-chat-bot/bot/pull/58
